{
  "hash": "8af002cf5bb0d1766603aa13f8cc1c8c",
  "result": {
    "markdown": "# Classical probability II  {#L06-classical-ii}\n\nWe continue looking at the classical probability $\\mathbb P(A) = |A|/|\\Omega|$, by looking at ways to enumerate $\\Omega$ and $A$. Last time we saw:\n\n* The multiplication principle: $n_1$ choices followed by $n_2$ choices, ..., up to $n_k$ choices gives $n_1 \\times n_2 \\times \\cdots \\times n_k$ choices in total.\n* Sampling $k$ objects out of $n$ with replacement gives $n^k$ choices.\n* Sampling $k$ objects out of $n$ without replacement gives $n^{\\underline{k}} = n(n-1)\\dots(n-k+1)$ choices.\n\n## Ordering  {#ordering}\n\n<!--\n:::: {.videowrap}\n::: {.videowrapper}\n<iframe src=\"https://www.youtube.com/embed/_kxbyjSaF_s\"></iframe>\n:::\n::::\n-->\n\n\n::: {.example}\n*Suppose a lecturer marks a pile of $n$ exam papers, all of which receive a different mark. What is the probability she ends up marking them in order from lowest scoring first in the pile to highest scoring last in the pile?*\n\nHere, the sample space $\\Omega$ is the set of all orderings of the $n$ exam papers by mark, and $A$ is the event that the papers are in order from lowest to highest scoring. It's clear that $|A| = 1$: since the exams scored different marks, there's only one way of putting the exams in the correct lowest-to-highest order. But what's $|\\Omega|$?\n\nThere are $n$ choices for the first exam paper to be marked. Then, for the second exam paper, there are $n - 1$ choices left, because the lecturer is not going to mark the same paper twice. There are $n-2$ choices for the third exam paper. And so on, until she has marked $n-1$ papers, and there is only 1 choice left for the final paper. So we have\n\\[ |\\Omega| = \\ff nn = n(n-1)(n-2)\\cdots3\\cdot2\\cdot1 = n! \\]\nways to order the exam papers.\n\nHence, the probability the papers are marked in order is\n\\[ \\mathbb P(A) = \\frac{|A|}{|\\Omega|} = \\frac{1}{n(n-1)\\cdots2\\cdot1} = \\frac{1}{n!} . \\]\n:::\n\nThis number\n\\[ n! = \\ff nn = n(n-1)(n-2)\\cdots3\\cdot2\\cdot1 \\]\nis called **$n$ factorial** and denoted $n!$. It is the number of ways that $n$ different objects can be ordered.\n\nThe factorial $n!$ gets very large very quickly. **Stirling's formula** gives the approximation\n$n! \\approx \\sqrt{2\\pi n} \\, \\mathrm{e}^{-n} \\, n^n$.\n\n::: {.example}\nSuppose you shuffle a pack of cards. The resulting ordering of the deck has $52!$ possibilities. This is an unimaginably huge number -- the exact value to 3 significant figures is\n\\[ 52! = 8.07 \\times 10^{67} , \\]\nwhile Stirling's formula gives the approximation\n\\[ 52! \\approx \\sqrt{2\\pi \\times 52} \\times \\mathrm{e}^{-52} \\times 52^{52} = 8.05 \\times 10^{67} . \\]\nThis is an 8 followed by 67 zeroes.\n\nIf every person on the planet (very roughly $10^{10}$) had shuffled a deck of cards one million ($10^6$) times a second for the entire lifetime of the universe (roughly $10^{17}$ seconds), they could only expect to have got through about $10^{33}$ shuffles.\nThis is only the most tiny, microscopic fraction of $52!$. So every time you have ever shuffled a deck of cards, it is essentially certain that you have created an ordering of the deck that has never existed before.\n:::\n\nIf we take the ratio of a bigger factorial $n!$ over a smaller factorial $j!$, we get lot of cancellation,\n\\begin{align*}\n\\frac{n!}{j!} &= \\frac{n(n-1) \\cdots(j+1)j(j-1) \\cdots 1}{j(j-1) \\cdots 1} \\\\\n  &= n(n-1) \\cdots (j+1) ,\n\\end{align*}\nbecause the last part of the product in the numerator cancels with the whole of the denominator. Replacing $j$ with $n-k$, this gives\n\\[ \\frac{n!}{(n-k)!} = n(n-1) \\cdots (n - k + 1) = \\ff{n}{k} . \\]\nThis gives a way of writing the falling factorial as the ratio of two (normal) factorials, which can sometimes be useful.\n\n<!--\nIt can sometimes be useful to write the falling factorial $\\ff nk$ in terms of the factorial, like this:\n\\begin{align*}\n\\ff nk &= n(n-1)\\cdots(n-k+1) \\\\\n  &= n(n-1)\\cdots(n-k+1)\\times\\frac{(n-k)(n-k-1)\\cdots2\\cdot1}{(n-k)(n-k-1)\\cdots2\\cdot1} \\\\\n  &= \\frac{n(n-1)\\cdots(n-k+1)(n-k)(n-k-1)\\cdots2\\cdot1}{(n-k)(n-k-1)\\cdots2\\cdot1} \\\\\n  &= \\frac{n!}{(n-k)!},\n\\end{align*}\nwhere the numbers from $n-k$ down to 1 cancel out.\n-->\n\n## Sampling without replacement in any order  {#combinations}\n\n<!--\n:::: {.videowrap}\n::: {.videowrapper}\n<iframe src=\"https://www.youtube.com/embed/s9MehuyRW6Q\"></iframe>\n:::\n::::\n-->\n\n\n::: {.example #lotto}\n*In the Lotto, the UK national lottery, you can buy a ticket for £2 and choose 6 numbers between 1 and 59. If your 6 numbers match the 6 numbers on the balls chosen by the lottery machine, you win the jackpot (usually between £2 million and £20 million, shared between the tickets that get all 6 numbers). If you buy a ticket, what is the probability you win the jackpot?*\n\nHere, $\\Omega$ is the set of all possible sets of 6 winning numbers, and $A$ is the set of numbers on your ticket. Clearly $|A| = 1$, but what is $|\\Omega|$?\n\nWell, the first ball out of the machine has 59 possibilities, the second ball has 58 possibilities, and so on, making\n\\[ 59 \\times 58 \\times 57 \\times 56 \\times 55 \\times 54 = \\ff{59}{6} . \\]\n\nBut this isn't the correct answer, because the same set of balls could be drawn from the machine in any order! The sets of balls $\\{1,2,3,4,5,6\\}$ and $\\{1,2,3,4,6,5\\}$ and $\\{6,5,4,3,2,1\\}$ are all the same set of numbers. How many ways can we see the same list of numbers? This is precisely the number of orderings of 6 balls, which we know is $6!$. So the number of possible sets of 6 balls to come out of the machine is actually\n\\[ \\binom{59}{6} = \\frac{\\ff{59}{6}}{6!} = \\frac{59 \\times 58 \\times 57 \\times 56 \\times 55 \\times 54}{6\\times5\\times4\\times3\\times2\\times1} \\approx 45 \\text{ million} . \\]\n\nThus the probability that your ticket wins the jackpot is\n\\[ \\mathbb P(A) = \\frac{|A|}{|\\Omega|} = \\frac{1}{\\binom{59}{6}} \\approx \\frac{1}{45 \\text{ million}} \\approx 0.000\\,000\\,02 . \\]\n:::\n\nHere, we have introduced the notation\n\\[ \\binom{n}{k} = \\frac{\\ff{n}{k}}{k!} = \\frac{n(n-1) \\cdots (n-k+1)}{k(k-1)\\cdots2\\cdot1}  \\]\nfor the number of ways to choose $k$ objects out of $n$ without replacement *and where the order they were chosen in doesn't matter*. This is called the **binomial coefficient**, although when we say it out loud we normally just say \"$n$ choose $k$\". (Another notation for the binomial coefficient is ${}^n C_k$.)\n\nIt can sometimes be useful to remember that $\\ff nk = n!/(n-k)!$ allows us to write the binomial coefficient in terms of the factorial function as\n\\[ \\binom nk = \\frac{\\ff nk}{(n-k)!} = \\frac{n!}{k!(n-k)!} . \\]\n\n\n::: {.example #akqj}\n*You are dealt a \"hand\" of 13 cards from a deck of 52 cards. What is the probability that you have the Ace, King, Queen, and Jack of Spades?*\n\nHere, $\\Omega$ is the set of all 13-card hands from the deck, and $A$ is the subset of those that contain the AKQJ of Spades.\n\nUsing the binomial coefficient notation, it's clear that\n\\[ |\\Omega| = \\binom{52}{13} = \\frac{52\\times51\\times\\cdots\\times41\\times40}{13\\times12\\times\\cdots\\times2\\times1} . \\]\n\nWhat about $|A|$? If we fix the fact that the hand contains the 4 cards AKQJ of Spades, then it also contains $13-4=9$ cards out of the other $52-4 = 48$ remaining cards in the deck. This makes\n\\[ |A| = \\binom{48}{9} = \\frac{48\\times47\\times\\cdots\\times41\\times40}{9\\times8\\times\\cdots\\times2\\times1}\\]\nhands.\n\nThus the probability that the hand contains AKQJ of Spades is\n\\[ \\mathbb P(A) = \\frac{|A|}{|\\Omega|} = \\frac{\\binom{48}{9}}{\\binom{52}{13}} . \\]\n\nConveniently, we can simplify the expression quite a lot, because plenty of cancellation will occur. We have\n\\begin{align*}\n\\mathbb P(A) = \\frac{\\binom{48}{9}}{\\binom{52}{13}}\n  &= \\frac{\\frac{48\\times47\\times\\cdots\\times41\\times40}{9\\times8\\times\\cdots\\times2\\times1}}{\\frac{52\\times51\\times\\cdots\\times41\\times40}{13\\times12\\times\\cdots\\times2\\times1}} \\\\\n  &= \\frac{48\\times47\\times\\cdots\\times41\\times40}{52\\times51\\times\\cdots\\times41\\times40} \\times \\frac{13\\times12\\times\\cdots\\times2\\times1}{9\\times8\\times\\cdots\\times2\\times1} \\\\\n  &= \\frac{13\\times12\\times11\\times10}{52\\times51\\times50\\times49} \\\\\n  &\\approx 0.0026 ,\n\\end{align*}\nor about 1 in every 380 hands.\n:::\n\n<!--\nThere's one other useful fact about the binomial coefficient we should mention.\n\n::: {.theorem}\n\\[ \\binom nk = \\binom{n}{n-k}. \\]\n:::\n\nWe'll give two different proofs of this fact.\n\n::: {.proof}\nWe can use the formula for the binomial coefficient in terms of the factorial function. This formula gives\n\\[ \\binom nk = \\frac{n!}{k!(n-k)!} \\qquad \\binom{n}{n-k} = \\frac{n!}{(n-k)!k!} . \\]\nIt's clear from the factorial expression that these two quantities are equal.\n:::\n\n::: {.proof}\nSuppose we have $n$ balls, and we want to paint $k$ of the red and the other $n-k$ blue. How many ways can we do this?\n\nOne way is to say there are $\\binom nk$ ways to choose the $k$ balls to paint red, then we are forced paint the other $n - k$ blue.\n\nAnother way is to say there are $\\binom{n}{n-k}$ to choose the $n-k$ balls to paint blue, then we are forced to paint the other $k$ red.\n\nWe have \"double counted\" the same quantity two different ways, so the answer must be the same, so\n\\[ \\binom nk = \\binom{n}{n-k}. \\]\n:::\n\nWhich proof do you prefer? (I strongly prefer the second proof, because I think it doesn't just *verify* that the theorem is true, but further explains *why* the result is true.)\n-->\n\n## Birthday problem  {#birthday}\n\n<!--\n:::: {.videowrap}\n::: {.videowrapper}\n<iframe src=\"https://www.youtube.com/embed/hNcCvJgKRXA\"></iframe>\n:::\n::::\n-->\n\n::: {.example}\n*There are $k = 23$ students in a class. What is the probability that at least two of the students share a birthday?*\n\nThis a famous problem, known as the \"birthday problem\". You may have seen this problem before -- but let's try to solve it using the techniques from this section of notes. If you haven't seen it before, you might like to guess what you think the answer might be. (We'll assume all days are equally likely for birthdays, and ignore the leap day 29 February.)\n\nThe sample space $\\Omega$ is the set of possible birthdays for the $k$ students. Clearly $|\\Omega| = 365^k$.\n\nLet $A$ be the even that at least two students share a birthday. Since this is an \"at least\" event, it seems like it might be a good idea to look instead at the complementary event $A^\\comp$. If $A$ is the event that there's at least one shared birthday, then $A^\\comp$ is the event that there are *no* shared birthdays; that is, $A^\\comp$ is the event that all $k$ students have *different* birthdays.\n\nSo what is $|A^\\comp|$, the number of ways the $k$ students can have different birthdays? Well, the first student can have any of the 365 days for their birthday. For them to have different birthdays, the second student only has 364 days available. Then the third student must avoid the birthday of students 1 and 2, so has 363 available days, and so on. We see that \n\\[ |A^\\comp| = 365 \\times 364 \\times \\cdots \\times (365 - k + 1) = 365^{\\underline{k}} . \\]\n\nHence, the probability at least two students share a birthday is\n\\[ \\mathbb P(A) = 1 - \\mathbb P(A^\\comp) = 1 - \\frac{365^{\\underline{k}}}{365^k} = 1 - \\frac{365}{365} \\cdot \\frac{364}{365} \\cdots \\frac{365-k+1}{365} . \\]\n\nSetting $k = 23$, we can calculate the required answer in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 23\n1 - prod((365:(365 - k + 1)) / 365)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5072972\n```\n:::\n:::\n\n\nThe probability is 50.7%. So it's more likely than not that at least two students share a birthday.\n:::\n\nSome people find it surprising that only 23 students have such a high probability of sharing a birthday, since 23 is so small compared to 365. But remember there are $\\binom{23}{2} = 253$ *pairs* of birthdays, and each of those 253 pairs is a potential match.\n\n\n## Summary  {#summary-L06 .unnumbered}\n\n::: {.mysummary}\n* Ordering $n$ objects can be done in $n! = n^{\\underline{n}} = n(n-1)\\cdots2\\cdot1$ ways.\n* The number of ways to sample $k$ objects out of $n$ when the order doesn't matter is given by the binomial coefficient $\\binom nk = \\ff{n}{k}/k!$.\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}