<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MATH1710 Probability and Statistics 1 - 16&nbsp; Normal distribution</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../sections/L16-exponential-multi.html" rel="next">
<link href="../sections/L15-continuous.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Normal distribution</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">MATH1710</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">About MATH1710</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Exploratory data analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L01-stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Summary statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L02-dataviz.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data visualisations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Probability</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L03-events.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sample spaces and events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L04-probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L05-classical-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classical probability I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L06-classical-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Classical probability II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L07-conditional.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Independence and conditional probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L08-two-theorems.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Two theorems on conditional probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L09-discrete-rv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discrete random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L10-expectation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Expectation and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L11-binomial-geometric.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Binomial and geometric distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L12-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Poisson distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L13-multi-rv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multiple random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L14-covariance.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Expectation and covariance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L15-continuous.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L17-normal.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L16-exponential-multi.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Exponential distribution and multiple continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L18-limit.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Limit theorems</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Bayesian statistics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L19-bayes-idea.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">The Bayesian idea</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L20-bayes-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">More Bayesian models</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Other stuff</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L21-summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">All questions answered</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/L22-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Exam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../R/R.html" class="sidebar-item-text sidebar-link">R Worksheets</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../writing.html" class="sidebar-item-text sidebar-link">Tips on writing mathematics</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#normal-definition" id="toc-normal-definition" class="nav-link active" data-scroll-target="#normal-definition"><span class="toc-section-number">16.1</span>  Definition of the normal distribution</a></li>
  <li><a href="#normal-properties" id="toc-normal-properties" class="nav-link" data-scroll-target="#normal-properties"><span class="toc-section-number">16.2</span>  Properties of the normal distribution</a></li>
  <li><a href="#normal-r" id="toc-normal-r" class="nav-link" data-scroll-target="#normal-r"><span class="toc-section-number">16.3</span>  Calculations using R</a></li>
  <li><a href="#normal-tables" id="toc-normal-tables" class="nav-link" data-scroll-target="#normal-tables"><span class="toc-section-number">16.4</span>  Calculations using statistical tables</a></li>
  <li><a href="#summary-L16" id="toc-summary-L16" class="nav-link" data-scroll-target="#summary-L16">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="L16-normal" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>When we studied discrete random variables, we studied a number of important families of distributions: the Bernoulli, binomial, geometric, and Poisson distributions. In this lecture, we’ll look at an extremely important distribution: the “normal” (or “Gaussian”) distribution.</p>
<section id="normal-definition" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="normal-definition"><span class="header-section-number">16.1</span> Definition of the normal distribution</h2>
<!--
:::: {.videowrap}
::: {.videowrapper}
<iframe src="https://www.youtube.com/embed/of84BBnJdgw"></iframe>
:::
::::


There's one very important distribution we need to talk about, which is the so-called "normal" (or "Gaussian") distribution.
-->
<div class="definition">
<p>If <span class="math inline">\(X\)</span> is a continuous random variable with PDF [ f_X(x) = ( - ) , ] then we say that <span class="math inline">\(X\)</span> has the <strong>normal distribution</strong> with expectation <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2 &gt; 0\)</span>, and write <span class="math inline">\(X \sim \mathrm N(\mu,\sigma^2)\)</span>.</p>
</div>
<p>(Many people call <span class="math inline">\(\mu\)</span> the “mean”, which is a slight misnomer.)</p>
<p>This PDF is the famous “bell curve”, where the centre of the bell is at <span class="math inline">\(x = \mu\)</span> and the width of the bell is controlled by the value of <span class="math inline">\(\sigma^2\)</span>. Note also that the PDF is symmetric about <span class="math inline">\(\mu\)</span>.</p>
<div class="cell" data-hash="L17-normal_cache/html/norm-pic-1_6c084f494c87c23536ff8817721ecf3b">
<div class="cell-output-display">
<p><img src="L17-normal_files/figure-html/norm-pic-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="L17-normal_cache/html/norm-pic-2_dfd63ea4374f54fc62e83dfdaec8b117">
<div class="cell-output-display">
<p><img src="L17-normal_files/figure-html/norm-pic-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>One important special case is <span class="math inline">\(\mu = 0\)</span> and <span class="math inline">\(\sigma^2 = 1\)</span>, in which case we say that <span class="math inline">\(Z \sim \mathrm N(0,1)\)</span> has the <strong>standard normal distribution</strong>. We typically write <span class="math inline">\(\phi\)</span> (lower-case “phi”), where [ (z) = e<sup>{-z</sup>2/2} ] for the PDF of a standard normal distribution, and write <span class="math inline">\(\Phi\)</span> (upper-case “Phi”), where [ (z) = P(Z z) = _{-}^z e<sup>{-y</sup>2/2}, dy ] for the CDF of a standard normal distribution.</p>
<p>The normal distribution is a very widely used distribution for modelling many things in real life.</p>
<ul>
<li>Measurement error with scientific instruments is typically modelled as a normal distribution with expectation <span class="math inline">\(\mu = 0\)</span>. The more precise the instrument, the lower the value of the variance <span class="math inline">\(\sigma^2\)</span>.</li>
<li>According to <a href="http://www1.maths.leeds.ac.uk/~voss/2019/MATH1712/index.html">a poll a few years ago</a>, the height of MATH1712 students in centimetres can be modelled well by a normal distribution with expectation <span class="math inline">\(\mu = 172\)</span> and variance <span class="math inline">\(\sigma^2 = 86\)</span>.</li>
<li>In financial models, it is often assumed that the logarithm of the daily change in a stock price follows a normal distribution. In this context, the expectation <span class="math inline">\(\mu\)</span> is known as the “drift” and the standard deviation <span class="math inline">\(\sigma\)</span> as the “volatility”. This “log-normal” model is the basis of the famous Black–Scholes model of financial markets.</li>
</ul>
<p>More generally, and for reasons we will come back to later, the normal distribution is good for modelling things where lots of little effects add together to make a bigger effect. We will also see later that many other distributions can be approximated by a normal distribution.</p>
<p>It’s generally difficult, or even impossible, to directly calculate probabilities of events concerning the normal distribution. Instead, one must use numerical approximations. We will discuss these further later in this section.</p>
</section>
<section id="normal-properties" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="normal-properties"><span class="header-section-number">16.2</span> Properties of the normal distribution</h2>
<!--
:::: {.videowrap}
::: {.videowrapper}
<iframe src="https://www.youtube.com/embed/4P6Xe1BbMn0"></iframe>
:::
::::
-->
<div id="norm-prop" class="theorem">
<p>Let <span class="math inline">\(X \sim \mathrm{N}(\mu, \sigma^2)\)</span> be a normally distributed random variable. Then:</p>
<ol type="1">
<li><span class="math inline">\(f_X(x)\)</span> is indeed a PDF, in that <span class="math inline">\(\displaystyle\int_{-\infty}^\infty f_X(x)\,\mathrm dx = 1\)</span>;</li>
<li><span class="math inline">\(\mathbb EX = \mu\)</span>;</li>
<li><span class="math inline">\(\Var(X) = \sigma^2\)</span>.</li>
</ol>
<p>In particular, if <span class="math inline">\(Z \sim \mathrm{N}(0, 1)\)</span> is a standard normal distribution, then <span class="math inline">\(\mathbb EZ = 0\)</span> and <span class="math inline">\(\Var(Z) = 1\)</span>.</p>
</div>
<p>We’ll give (non-examinable) proofs of these soon. But first we’ll note one other thing.</p>
<p>Let <span class="math inline">\(X \sim \mathrm{N}(\mu, \sigma^2)\)</span>, and consider the random variable <span class="math inline">\(Y = aX + b\)</span>. Then we know that <span class="math display">\[\begin{align*}
\mathbb E(aX + b) &amp;= a\mu + b , \\
\Var(aX + b) &amp;= a^2 \sigma^2 .
\end{align*}\]</span> In fact, it can be shown that <span class="math inline">\(aX + b\)</span> is normally distributed too; that is, <span class="math inline">\(aX + b \sim \mathrm{N}(a\mu + b, a^2 \sigma^2)\)</span>. Importantly, if we take <span class="math inline">\(a = 1/\sigma\)</span> and <span class="math inline">\(b = -\mu/\sigma\)</span>, then we see that [ Z = (0, 1) . ] In other words, we can stretch and scale any normal random variable to turn it into a standard normal random variable. This is known as “standardisation” and will be useful later.</p>
<p>We can also use standardisation to help us prove Theorem @ref(thm:norm-prop).</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>(Non-examinable)</em> By using standardisation, it suffices to prove the theorem for a standard normal random variable <span class="math inline">\(X \sim \mathrm{N}(0,1)\)</span>.</p>
<p>For part 1, we need to show that [ I = _{-}<sup>e</sup>{-x^2/2}, dx = 1 . ] To prove this we use one of the most outrageous tricks in mathematics! The first part of the trick is that, instead of calculating the integral itself <span class="math inline">\(I\)</span>, we can instead calculate the square of the integral <span class="math inline">\(I^2\)</span>, which we also need to show is equal to 1. This is <span class="math display">\[\begin{align*}
  I^2 &amp;= \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty \mathrm e^{-x^2/2}\, \mathrm dx \times \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty \mathrm e^{-y^2/2}\, \mathrm dy\\
    &amp;= \frac{1}{2\pi} \int_{-\infty}^\infty \int_{-\infty}^\infty  \mathrm e^{-x^2/2}\,\mathrm e^{-y^2/2} \, \mathrm dx\, \mathrm dy \\
    &amp;= \frac{1}{2\pi} \int_{-\infty}^\infty \int_{-\infty}^\infty  \mathrm e^{-(x^2+y^2)/2}\,\mathrm dx\, \mathrm dy .
\end{align*}\]</span> The second part of the outrageous trick is notice that the appearance of <span class="math inline">\(x^2 + y^2\)</span> suggests it might be useful to transfer from cartesian coordinates <span class="math inline">\((x,y)\)</span> to polar coordinates <span class="math inline">\((r, \theta)\)</span>. Recalling that <span class="math inline">\(x^2 + y^2 = r^2\)</span> and <span class="math inline">\(\mathrm dx\, \mathrm dy = r\, \mathrm dr \,\mathrm d\theta\)</span>, we have <span class="math display">\[\begin{align*}
  I^2 &amp;= \frac{1}{2\pi} \int_{0}^{2\pi} \int_{0}^\infty  \mathrm e^{-r^2/2}\,r\,\mathrm dr\, \mathrm d\theta \\
    &amp;= \frac{1}{2\pi} \, 2\pi\int_{0}^\infty  r\, \mathrm e^{-r^2/2}\,\mathrm dr \\
    &amp;= \left[ -\mathrm e^{-r^2/2} \right]_0^\infty \\
    &amp;= - 0 -(-1) \\
    &amp;= 1 ,
\end{align*}\]</span> and we’re done.</p>
<p>For part 2, we need to show that <span class="math inline">\(\mathbb EX = 0\)</span>. We have <span class="math display">\[\begin{align*}
\mathbb EX &amp;= \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty} x\,  \mathrm e^{-x^2/2}\, \mathrm dx \\
  &amp;= \frac{1}{\sqrt{2\pi}} \left[-\mathrm e^{-x^2/2}\right]_{-\infty}^\infty \\
  &amp;= -0 - (-0) \\
  &amp;= 0 ,
\end{align*}\]</span> as required.</p>
<p>For part 3, we need to show that <span class="math inline">\(\mathbb EX^2 = 1\)</span>. Using integration by parts with <span class="math inline">\(u = x\)</span>, <span class="math inline">\(v' = x\,\mathrm e^{-x^2/2}\)</span>, we have <span class="math display">\[\begin{align*}
\mathbb EX^2 &amp;= \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty} x^2\,  \mathrm e^{-x^2/2}\, \mathrm dx \\
  &amp;= \frac{1}{\sqrt{2\pi}} \left[-x \mathrm e^{-x^2/2}\right]_{-\infty}^\infty + \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty \mathrm e^{-x^2/2} \, \mathrm dx \\
  &amp;= 0 + \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty \mathrm e^{-x^2/2} \, \mathrm dx .
\end{align*}\]</span> But this integral on the right is just the integral <span class="math inline">\(I\)</span> of the PDF as above, which we know equals 1, as required.</p>
</div>
<p>There is one last property of the normal distribution that we won’t use directly in this module, but is perhaps worth knowing anyway.</p>
<div class="theorem">
<p>If <span class="math inline">\(X \sim \mathrm{N}(\mu_X, \sigma^2_X)\)</span> and <span class="math inline">\(Y\sim \mathrm{N}(\mu_Y, \sigma^2_Y)\)</span> are independent, then [ X+Y (_X + _Y, <sup>2_X+</sup>2_Y) . ]</p>
</div>
</section>
<section id="normal-r" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="normal-r"><span class="header-section-number">16.3</span> Calculations using R</h2>
<p>We will try to answer a number of questions about the normal distribution.</p>
<div class="thpart">
<p><strong>Question 1.</strong> <em>A fiberoptic fibre is manufactured with an average width of 8 nanometres (nm), with a standard deviation of 0.04 nm. Fibres that are wider than 8.1 nm fail testing and must be discarded. If the manufactured width is modelled as normally distributed, then what proportion of fibres pass the test?</em></p>
<p>Let <span class="math inline">\(X \sim \mathrm{N}(8, 0.04^2)\)</span> denote the width of a random fibre, measured in nanometres. Then this question required us to find [ F(8.15) = P(X ) = _{-}^{8.1} (- ) , dx . ]</p>
<p>Unfortunately, it is not possible to calculate this integral exactly. However, computers can approximate this integral very accurately and very quickly. In R, this is done with the <code>pnorm()</code> function, which calculates the CDF of a normal distribution. <code>pnorm()</code> typically takes three arguments:</p>
<ol type="1">
<li>the first argument is the value <span class="math inline">\(x\)</span> at which we wish to evaluate the CDF;</li>
<li>the second argument is the expectation <span class="math inline">\(\mu\)</span> of the normal distribution;</li>
<li>the third argument is the standard deviation <span class="math inline">\(\sigma\)</span> of the normal distribution. (Note that this third argument is the <em>standard deviation</em> <span class="math inline">\(\sigma\)</span> and not the variance <span class="math inline">\(\sigma^2\)</span>. This is an easy mistake to make!)</li>
</ol>
<p>So here, the number we want is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">8.1</span>, <span class="dv">8</span>, <span class="fl">0.04</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9937903</code></pre>
</div>
</div>
<p>We see that roughly 99.4% of fibres pass the test.</p>
</div>
<div class="thpart">
<p><strong>Question 2.</strong> <em>Let <span class="math inline">\(Z \sim \mathrm{N}(0,1)\)</span>. What is <span class="math inline">\(\mathbb P(Z \leq 1.45)\)</span>?</em></p>
<p>This is asking for <span class="math inline">\(\Phi(1.45) = \mathbb P(Z \leq 1.45)\)</span>. This is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.45</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9264707</code></pre>
</div>
</div>
<p>But in fact, the standard normal distribution CDF <span class="math inline">\(\Phi\)</span> is so common that R allows you to omit the values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> if they are 0 and 1 respectively. So you can save yourself a few keystrokes by simply writing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9264707</code></pre>
</div>
</div>
</div>
<div class="thpart">
<p><strong>Question 3.</strong> <em>Let <span class="math inline">\(Z \sim \mathrm{N}(0,1)\)</span>. What is <span class="math inline">\(\mathbb P(Z &gt; 0.33)\)</span>?</em></p>
<p>This is asking for the upper-tail probability. The direct way to get R to solve this is to use the <code>lower.tail = FALSE</code> option that we discussed in <a href="#r-work">R Worksheet 7</a>. That is, we use:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">0.33</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3707</code></pre>
</div>
</div>
<p>Alternatively, we could use the fact that <span class="math inline">\(\mathbb P(Z &gt; z) = 1 - \mathbb P(Z \leq z) = 1 - \Phi(z)\)</span>. Then we could equally well calculate this as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fl">0.33</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3707</code></pre>
</div>
</div>
</div>
<div class="thpart">
<p><strong>Question 4.</strong> <em>We return to the fiberoptic model <span class="math inline">\(X \sim \mathrm{N}(8, 0.04^2)\)</span> from Question 1. Fibres can be awarded a special “high quality” stamp if their width is between 7.95 and 8.05 nm. What proportion of these fibres qualify?</em></p>
<p>This is asking for <span class="math inline">\(\mathbb P(7.95 \leq X \leq 8.05)\)</span>. But we can calculate this as [ P(7.95 X ) = P(X ) - P(X &lt; 7.95) = F(8.05) - F(7.95) .] (Formally, this is because [ {X &lt; 7.95} {7.95 X } = {X } ] is a disjoint union, so we can use Axiom 3.)</p>
<p>So the proportion of qualifying fibres is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.04</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">8.05</span>, mu, sigma) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fl">7.95</span>, mu, sigma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7887005</code></pre>
</div>
</div>
<p>or about 79%.</p>
</div>
<div class="thpart">
<p><strong>Question 5.</strong> <em>We stay with the fiberoptic model <span class="math inline">\(X \sim \mathrm{N}(8, 0.04^2)\)</span> from Questions 1 and 4. The manufacturer wants to be able to advertise that 99.9% of their fibres are between lower and upper limits <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. What values of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> can they promise?</em></p>
<p>Is <span class="math inline">\(F\)</span> is the CDF of this distribution, then we are looking for <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> such that <span class="math inline">\(F(x) = 0.0005\)</span> and <span class="math inline">\(F(y) = 0.9995\)</span>. That way, <span class="math inline">\(F(y) - F(x) = 0.999\)</span>, so we have 99.9% of fibres within that interval and 0.05% outside either side.</p>
<p>You may remember from R Worksheet 7 that the inverse <span class="math inline">\(F^{-1}\)</span> of the CDF is called the <strong>quantile function</strong>. Here, we want <span class="math inline">\(F^{-1}(0.0005)\)</span> and <span class="math inline">\(F^{-1}(0.9995)\)</span>. The quantile function for the normal distribution in R is <code>qnorm()</code>. (It also has a <code>lower.tail = FALSE</code> option, which is sometimes useful.) So we can use</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.04</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">qnorm</span>(<span class="fl">0.0005</span>, mu, sigma), <span class="fu">qnorm</span>(<span class="fl">0.9995</span>, mu, sigma))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.868379 8.131621</code></pre>
</div>
</div>
<p>We see that we can guarantee that 99.9% of fibres are between roughly 7.87 and 8.13 nm wide.</p>
</div>
</section>
<section id="normal-tables" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="normal-tables"><span class="header-section-number">16.4</span> Calculations using statistical tables</h2>
<p>Doing normal calculations with R is all very well. But what if you accidentally built a time machine and got transported back to Victorian times. Then how would you perform calculations with the normal distribution?</p>
<p>In the olden days, someone would (using some enormous computer the size of a room, or whatever) calculate lots of values of <span class="math inline">\(\Phi(x)\)</span>, the CDF of the standard normal distribution, and publish them in a book of statistical tables. An example of this is <a href="https://mpaldridge.github.io/math1710/stat-tab.pdf"><strong>this page of normal distribution tables</strong> [PDF]</a> that will appear on the final page of your exam. (Like the Victorian times, your exam is another place R will not be available but statistical tables will be.)</p>
<p>We will return to the same questions we answered in the previous subsection, although in a slightly different order.</p>
<div class="thpart">
<p><strong>Question 2.</strong> <em>Let <span class="math inline">\(Z \sim \mathrm{N}(0,1)\)</span>. What is <span class="math inline">\(\mathbb P(Z \leq 1.45)\)</span>?</em></p>
<p>As we noted before, this is asking for <span class="math inline">\(\Phi(1.45) = \mathbb P(Z \leq 1.45)\)</span>. Consulting the <a href="https://mpaldridge.github.io/math1710/stat-tab.pdf">statistical tables</a>, we see that the value of <span class="math inline">\(\Phi(1.45)\)</span> is listed on the table. Specifically, we see from column 3, row 10 of Table 1 that <span class="math inline">\(\Phi(1.45) = 0.9265\)</span>. This is the same value as we got from R (although we get fewer decimal places from the table).</p>
</div>
<div class="thpart">
<p><strong>Question 1.</strong> <em>A fiberoptic fibre is manufactured with an average width of 8 nanometres (nm), with a standard deviation of 0.04 nm. Fibres that are wider than 8.1 nm fail testing and must be discarded. If the manufactured width is modelled as normally distributed, then what proportion of fibres pass the test?</em></p>
<p>If <span class="math inline">\(X \sim \mathrm{N}(8, 0.04^2)\)</span>, then this asks for <span class="math inline">\(F_X(8.1) = \mathbb P(X \leq 8.1)\)</span>. However, unfortunately the statistical tables only have the CDF <span class="math inline">\(\Phi\)</span> for the standard normal distribution <span class="math inline">\(\mathrm N(0,1)\)</span>. So we are going to have “standardise” <span class="math inline">\(X\)</span>; that is, convert <span class="math inline">\(X\)</span> to a standard normal distribution. Recall from above that we standardise a normal random variable by subtracting the expectation <span class="math inline">\(\mu\)</span> and dividing by the standard deviation <span class="math inline">\(\sigma\)</span>. So in this case, we have [ Z = = (0,1) . ]</p>
<p>Using this, we can write [ P(X ) = P ( ) = P(Z ) = (2.5). ] We can then look up <span class="math inline">\(\Phi(2.5)\)</span> in Table 1. We see from the first row of the last column that <span class="math inline">\(\Phi(2.5) = 0.9938\)</span>. This matches the answer we got from R.</p>
</div>
<div class="thpart">
<p><strong>Question 3.</strong> <em>Let <span class="math inline">\(Z \sim \mathrm{N}(0,1)\)</span>. What is <span class="math inline">\(\mathbb P(Z &gt; 0.33)\)</span>?</em></p>
<p>The statistical tables only have <span class="math inline">\(\Phi(z) = \mathbb P(Z \leq z)\)</span>. But as we noted above, <span class="math inline">\(\mathbb P(Z &gt; 0.33) = 1 - \Phi(0.33)\)</span>. The tables don’t have <span class="math inline">\(\Phi(0.33)\)</span> either, though, because they jump straight from <span class="math inline">\(\Phi(0.30)\)</span> to <span class="math inline">\(\Phi(0.35)\)</span>. We have two choices of what to do here.</p>
<p>First choice, which is appropriate when an approximate answer will suffice, is simply to take the nearest value in the table, which here is <span class="math inline">\(0.35\)</span>. Hence [ P(Z &gt; 0.33) = 1 - (0.33) - (0.35) = 1 - 0.6368 = 0.3632 . ] This is pretty close to the true answer <span class="math inline">\(0.3707\)</span> we saw before: about a 2% error.</p>
<p>Second choice, which is more work but gets a more accurate answer, is to use interpolation. We know from the table that <span class="math inline">\(\Phi(0.30) = 0.6179\)</span> and <span class="math inline">\(\Phi(0.35) = 0.6368\)</span>. To “interpolate”, we assume that the graph of <span class="math inline">\(\Phi\)</span> follows a straight line between <span class="math inline">\((0.30, 0.6179)\)</span> and <span class="math inline">\((0.35, 0.6368)\)</span>. (In fact, <span class="math inline">\(\Phi\)</span> has a slightly curve, so isn’t <em>quite</em> straight.) As the statistical tables state, the interpolation is to take [ (x) = (x_1) + (x_2) .] In our case, if we take <span class="math inline">\(x_1 = 0.30\)</span> and <span class="math inline">\(x_2 = 0.35\)</span> as the interpolation points for <span class="math inline">\(x = 0.33\)</span>, we get the approximation [ (0.33) = 0.4 (0.30) + 0.6 (0.35) = 0.4 + 0.6 = 0.6292 ] This is off by only 0.01%; a very accurate approximation.</p>
</div>
<p>On problem sheets or in the exam, you will be told if an interpolation is necessary.</p>
<div class="thpart">
<p><strong>Question 4.</strong> <em>We return to the fiberoptic model <span class="math inline">\(X \sim \mathrm{N}(8, 0.04^2)\)</span> from Question 1. Fibres can be awarded a special “high quality” stamp if their width is between 7.95 and 8.05 nm. What proportion of these fibres qualify?</em></p>
<p>As noted above, this is asking for <span class="math inline">\(\mathbb P(7.95 \leq X \leq 8.05)\)</span>. To allow us to use our statistical tables, we will have to standardise. We get <span class="math display">\[\begin{align*}
\mathbb P(7.95 \leq X \leq 8.05)
  &amp;= \mathbb P \left(\frac{7.95 - 8}{0.04} \leq \frac{X - 8}{0.04} \leq \frac{8.05 - 8}{0.04}\right) \\
  &amp;= \mathbb P(-1.25 \leq Z \leq 1.25) \\
  &amp;= \Phi(1.25) - \Phi(-1.25) .
\end{align*}\]</span> We can find <span class="math inline">\(\Phi(1.25) = 0.8944\)</span> from the table. But the table only gives <span class="math inline">\(\Phi(x)\)</span> for positive <span class="math inline">\(x\)</span>, so we can’t look up <span class="math inline">\(\Phi(-1.25)\)</span>.</p>
<p>Instead, we can use the symmetry of the normal distribution. Because the standard normal is symmetric about 0, we have that <span class="math inline">\(\mathbb P(Z \leq -1.25) = \mathbb P(Z &gt; 1.25)\)</span>.</p>
<div class="cell" data-hash="L17-normal_cache/html/phiz-exm_0dc3c9e1acf5f26123beecc0fa94b359">
<div class="cell-output-display">
<p><img src="L17-normal_files/figure-html/phiz-exm-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Therefore, we have [ (-1.25) = P(Z &gt; 1.25) = 1 - (1.25) = 1 - 0.8944 = 0.1056]</p>
<p>Putting this all together, we get [P(7.95 X ) = 0.8944 - 0.1056 = 0.7888 , ] which is the same thing as we got from R (up to a small rounding error in the fourth decimal place).</p>
</div>
<div class="thpart">
<p><strong>Question 5.</strong> <em>We stay with the fiberoptic model <span class="math inline">\(X \sim \mathrm{N}(8, 0.04^2)\)</span> from Questions 1 and 4. The manufacturer wants to be able to advertise that 99.9% of their fibres are between lower and upper limits <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. What values of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> can they promise?</em></p>
<p>Recall that this meant we were looking for the quantiles <span class="math inline">\(F^{-1}(0.0005)\)</span> and <span class="math inline">\(F^{-1}(0.9995)\)</span>; that is, the values <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> such that <span class="math inline">\(\mathbb P(X \leq x) = 0.0005\)</span> and <span class="math inline">\(\mathbb P(X \leq x) = 0.9995\)</span>. Table 2 of the <a href="https://mpaldridge.github.io/math1710/stat-tab.pdf">statistical tables</a> does show us some quantiles for a standard normal. How can we use these?</p>
<p>Let’s start with the second case. The key here is to “undo” the standardisation. That is, if <span class="math inline">\(Z \sim \mathrm{N}(0,1)\)</span>, then <span class="math inline">\(X = \sigma Z + \mu \sim \mathrm{N}(\mu, \sigma^2)\)</span>. The table tells us that <span class="math inline">\(\Phi^{-1}(0.9995) = 3.2905\)</span>; that is, that <span class="math inline">\(\mathbb P(Z \leq 3.2905) = 0.9995\)</span>. Then by “un-standardising”, we have [ 0.9995 = P(Z ) = P(0.04Z + 8 + 8) = P(X ) . ] This the upper quantile we are after is <span class="math inline">\(8.1316\)</span>.</p>
<p>For the lower quantile, we can use symmetry again. Thus the <span class="math inline">\(0.0005 = 1 - 0.9995\)</span> quantile for <span class="math inline">\(Z\)</span> is minus the previous quantile; that is, <span class="math inline">\(-3.2905\)</span>. Hence the lower quantile we want is [0.04(-3.2905) + 8 = 7.8684. ] These match the answers we got with R.</p>
</div>
<p>I feel I shouldn’t finish with this subsection before addressing the following question some readers may be asking themselves: <em>Now that we have R (and other computing methods), what’s the point learning to answer questions using statistical tables?</em> I might suggest a few possible answers to this question:</p>
<ol type="1">
<li>Although using statistical tables is an archaic skill, in order to use the statistical tables, you will need to know and be able to apply many facts about probability distributions in general and the normal distribution in particular. So this is a good way to learn those facts and practice their application.</li>
<li>Someone has to write the computer program, and these people need to be able to do the sorts of conversions we will learn about here. So these are useful skills for mathematician–programmers to learn.</li>
<li>Being able to standardise normal distributions, approximate other distributions by normal distributions (see Lecture 18), and so on, are actually important to be able to solve purely mathematical problems, quite outside of merely performing calculations.</li>
<li>Yes, you are right, this is a pointless skill for us to teach you.</li>
</ol>
<p>I am mostly convinced by answers 1 to 3, although I must admit that answer 4 isn’t totally without merit.</p>
</section>
<section id="summary-L16" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary-L16">Summary</h2>
<div class="mysummary">
<ul>
<li>The normal distribution has PDF [ f(x) = (- ) .] It has expectation <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>.</li>
<li>The standard normal distribution has <span class="math inline">\(\mu = 0\)</span> and <span class="math inline">\(\sigma^2 = 1\)</span>.</li>
<li>The CDF of a normal distribution can be calculated in R with the <code>pnorm()</code> function. It can also be calculated using <a href="https://mpaldridge.github.io/math1710/stat-tab.pdf">statistical tables</a> and by “standardising”.</li>
</ul>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../sections/L15-continuous.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Continuous random variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../sections/L16-exponential-multi.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Exponential distribution and multiple continuous random variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>